version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: framer-motion
    versions:
    - 3.2.1
    - 3.3.0
    - 3.6.2
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.35
    - 14.14.37
  - dependency-name: "@next/mdx"
    versions:
    - 10.0.5
    - 10.0.7
    - 10.0.8
    - 10.0.9
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
    - 26.0.20
    - 26.0.21
  - dependency-name: "@babel/plugin-proposal-nullish-coalescing-operator"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: "@types/react-modal"
    versions:
    - 3.10.6
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: y18n
    versions:
    - 4.0.1
