sudo: required
language: node_js
node_js:
  - "10"
  - "11"
  - "12"
branches:
  only:
    - master
    - dev
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
  - npm install -g codecov
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK
